import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/layout/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="pt-BR" className="h-full antialiased">
      <Header />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}